"""
OphAgent v0.2.2
真实单图 lightweight vision-language reasoning demo.

流程：
1. 调用已有 infer_classifier 做真实分类推理
2. 调用已有 gradcam 生成真实 CAM
3. 将 prediction / confidence / CAM 信息转成 structured findings
4. 生成中文 clinical-style summary
5. 保存 case-level artifacts

注意：
本 demo 不训练医学 VLM。
它是 classification + explainability + structured findings + report generation 的轻量 workflow。
"""

import argparse
import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from typing import Dict, Optional

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT))

from findings.finding_generator import generate_case_findings
from reasoning.report_generator import generate_report


def run_command(cmd):
    """运行 shell command，并返回 stdout。"""

    print("[RUN]", " ".join(cmd))

    result = subprocess.run(
        cmd,
        cwd=str(PROJECT_ROOT),
        text=True,
        capture_output=True,
        check=False,
    )

    if result.stdout:
        print(result.stdout)

    if result.stderr:
        print(result.stderr)

    if result.returncode != 0:
        raise RuntimeError(f"Command failed: {' '.join(cmd)}")

    return result.stdout


def parse_infer_output(stdout: str) -> Dict[str, object]:
    """从 infer_classifier 的终端输出中解析 prediction / raw_class / confidence。"""

    prediction: Optional[str] = None
    raw_class: Optional[str] = None
    confidence: Optional[float] = None

    for line in stdout.splitlines():
        line = line.strip()

        if line.startswith("Prediction:"):
            prediction = line.split("Prediction:", 1)[1].strip()

        elif line.startswith("Raw Class:"):
            raw_class = line.split("Raw Class:", 1)[1].strip()

        elif line.startswith("Confidence:"):
            confidence = float(line.split("Confidence:", 1)[1].strip())

    if prediction is None or raw_class is None or confidence is None:
        raise ValueError(
            "Failed to parse infer output. "
            "Expected Prediction / Raw Class / Confidence in stdout."
        )

    return {
        "prediction": prediction,
        "raw_class": raw_class,
        "confidence": confidence,
    }


def copy_original_image(image_path: Path, case_dir: Path) -> Path:
    """复制原图到 artifact folder。"""

    case_dir.mkdir(parents=True, exist_ok=True)

    dst = case_dir / f"original{image_path.suffix.lower()}"
    shutil.copy2(image_path, dst)

    return dst


def save_artifacts(
    image_path: Path,
    saved_original_path: Path,
    case_findings,
    report: str,
    case_dir: Path,
    infer_stdout: str,
    cam_stdout: str,
):
    """保存 findings / report / metadata。"""

    findings_path = case_dir / "findings.json"
    report_path = case_dir / "report.txt"
    metadata_path = case_dir / "metadata.json"

    with findings_path.open("w", encoding="utf-8") as f:
        json.dump(case_findings.to_dict(), f, ensure_ascii=False, indent=2)

    with report_path.open("w", encoding="utf-8") as f:
        f.write(report)

    metadata = {
        "image_path": str(image_path),
        "saved_original": str(saved_original_path),
        "prediction": case_findings.prediction,
        "raw_class": case_findings.raw_class,
        "confidence": case_findings.confidence,
        "cam_method": case_findings.cam_method,
        "cam_target_layer": case_findings.cam_target_layer,
        "cam_output_path": case_findings.cam_output_path,
        "created_at": datetime.now().isoformat(timespec="seconds"),
        "workflow": "single_image_real_infer_and_cam",
        "note": (
            "This artifact was generated by OphAgent v0.2.2 lightweight "
            "vision-language reasoning workflow. It is for research/demo use only."
        ),
        "infer_stdout": infer_stdout,
        "cam_stdout": cam_stdout,
    }

    with metadata_path.open("w", encoding="utf-8") as f:
        json.dump(metadata, f, ensure_ascii=False, indent=2)

    print(f"[OK] original saved to: {saved_original_path}")
    print(f"[OK] findings saved to: {findings_path}")
    print(f"[OK] report saved to: {report_path}")
    print(f"[OK] metadata saved to: {metadata_path}")


def main():
    parser = argparse.ArgumentParser(
        description="OphAgent v0.2.2 single-image VL reasoning demo"
    )

    parser.add_argument("--image", required=True, help="输入眼底图像路径")
    parser.add_argument("--config", required=True, help="模型配置文件")
    parser.add_argument("--checkpoint", required=True, help="模型 checkpoint")
    parser.add_argument("--class-to-idx", required=True, help="class_to_idx.json")

    parser.add_argument(
        "--method",
        default="hirescam",
        help="CAM 方法，默认 hirescam",
    )
    parser.add_argument(
        "--target-layer",
        default="stage3",
        help="CAM 目标层，默认 stage3",
    )
    parser.add_argument(
        "--output-dir",
        default="experiments/v0_2_2_vl_reasoning_demo/case_real_001",
        help="artifact 输出目录",
    )

    args = parser.parse_args()

    image_path = Path(args.image)
    case_dir = Path(args.output_dir)

    cam_output_dir = case_dir / "cam"

    print("========== OphAgent v0.2.2 VL Reasoning Demo ==========")

    infer_cmd = [
        sys.executable,
        "-m",
        "models.classifiers.infer_classifier",
        "--image",
        args.image,
        "--config",
        args.config,
        "--checkpoint",
        args.checkpoint,
        "--class_to_idx",
        args.class_to_idx,
    ]

    infer_stdout = run_command(infer_cmd)
    infer_result = parse_infer_output(infer_stdout)

    cam_cmd = [
        sys.executable,
        "-m",
        "explain.gradcam",
        "--image",
        args.image,
        "--config",
        args.config,
        "--checkpoint",
        args.checkpoint,
        "--class-to-idx",
        args.class_to_idx,
        "--method",
        args.method,
        "--target-layer",
        args.target_layer,
        "--output",
        str(cam_output_dir),
    ]

    cam_stdout = run_command(cam_cmd)

    saved_original_path = copy_original_image(
        image_path=image_path,
        case_dir=case_dir,
    )

    case_findings = generate_case_findings(
        image_path=args.image,
        prediction=infer_result["prediction"],
        raw_class=infer_result["raw_class"],
        confidence=infer_result["confidence"],
        topk_predictions=[
            {
                infer_result["prediction"]: infer_result["confidence"],
            }
        ],
        cam_method=args.method,
        cam_target_layer=args.target_layer,
        cam_output_path=str(cam_output_dir),
    )

    report = generate_report(case_findings)

    print("========== 中文摘要 ==========")
    print(report)
    print("==============================")

    save_artifacts(
        image_path=image_path,
        saved_original_path=saved_original_path,
        case_findings=case_findings,
        report=report,
        case_dir=case_dir,
        infer_stdout=infer_stdout,
        cam_stdout=cam_stdout,
    )

    print("[DONE] Single-image VL reasoning workflow finished")


if __name__ == "__main__":
    main()
