"""v0.6.1 报告生成 Provider 抽象。

本模块只提供确定性的报告生成 Provider：

- TemplateProvider：确定性模板报告生成器，用作安全回退路径。
- MockLLMProvider：确定性 Mock LLM 生成器，用于测试安全检查器。

真实 LLM Provider，例如 OpenAIProvider、ClaudeProvider 或本地模型 Provider，
刻意延后到 v0.6.2，以避免 v0.6.1 被 API Key、网络调用、成本和输出不稳定性干扰。
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Any, Literal


MockLLMMode = Literal["safe", "unsafe_diagnosis", "unsafe_cam", "unsafe_mixed"]
ReportProviderName = Literal["template", "mock_llm"]


@dataclass(frozen=True)
class ReportProviderResult:
    """Provider 生成结果。

    Attributes:
        provider: Provider 名称，例如 "template" 或 "mock_llm"。
        text: 生成出的 Markdown 报告草稿。
        metadata: 与本次生成相关的元信息，例如 mock 模式、是否确定性、是否调用真实 LLM。
    """

    provider: str
    text: str
    metadata: dict[str, object]


class TemplateProvider:
    """确定性模板报告生成器。

    该 Provider 用作安全回退路径。当 Mock LLM 草稿未通过 safety checker 时，
    renderer 应回退到该模板报告，避免不安全文本进入最终 report.html。
    """

    name = "template"

    def generate(self, prompt: str, case_data: dict[str, Any] | None = None) -> ReportProviderResult:
        """生成保守的模板式病例报告草稿。

        Args:
            prompt: 受约束 prompt。模板 Provider 当前不依赖 prompt 内容，但保留该参数以统一接口。
            case_data: 病例结构化数据，通常来自 prediction.json、findings.json、validation.json 等。

        Returns:
            ReportProviderResult: 确定性的模板报告草稿及其生成元信息。
        """
        case_data = case_data or {}

        prediction = case_data.get("prediction", {})
        findings = case_data.get("findings", {})

        predicted_label = prediction.get("predicted_label", "not available")
        confidence = prediction.get("confidence", "not available")

        text = f"""# Evidence-Bottleneck Case Report Draft

## Generation Mode

This report was generated by the deterministic template provider.

## Model Prediction

- Predicted label: {predicted_label}
- Confidence: {confidence}

## Structured Findings

The report is based only on structured findings available in the case artifact.

Findings summary:

{findings if findings else "No structured finding summary was provided."}

## Evidence Boundary

CAM or heatmap outputs are treated as weak visual evidence only. They are not lesion segmentation, lesion localization, or clinical diagnosis.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

        return ReportProviderResult(
            provider=self.name,
            text=text,
            metadata={
                "deterministic": True,
                "provider_type": "template",
                "provider_version": "v0.6.2-template-provider",
                "fallback_capable": True,
            },
        )


class MockLLMProvider:
    """确定性 Mock LLM 报告生成器。

    该 Provider 不调用真实 LLM，而是用固定文本模拟不同类型的 LLM 输出。
    主要目的不是生成高质量报告，而是为 safety_checker.py 提供可复现测试样例。
    """

    name = "mock_llm"

    def __init__(self, mode: MockLLMMode = "safe") -> None:
        """初始化 Mock LLM Provider。

        Args:
            mode: Mock 输出模式。
                - safe: 安全草稿，应通过 safety checker。
                - unsafe_diagnosis: 包含临床诊断越权表述。
                - unsafe_cam: 包含 CAM / heatmap 夸大表述。
                - unsafe_mixed: 同时包含多类不安全表述。
        """
        self.mode = mode

    def generate(self, prompt: str, case_data: dict[str, Any] | None = None) -> ReportProviderResult:
        """生成确定性的 Mock LLM 报告草稿。

        Args:
            prompt: 受约束 prompt。Mock Provider 当前不解析 prompt，但保留该参数以模拟真实 Provider 接口。
            case_data: 病例结构化数据。当前 Mock 输出不依赖该字段，后续可用于构造更贴近真实 case 的草稿。

        Returns:
            ReportProviderResult: Mock LLM 报告草稿及其生成元信息。

        Raises:
            ValueError: 当 mock mode 不受支持时抛出。
        """
        if self.mode == "safe":
            text = self._generate_safe_report()
        elif self.mode == "unsafe_diagnosis":
            text = self._generate_unsafe_diagnosis_report()
        elif self.mode == "unsafe_cam":
            text = self._generate_unsafe_cam_report()
        elif self.mode == "unsafe_mixed":
            text = self._generate_unsafe_mixed_report()
        else:
            raise ValueError(f"Unsupported mock LLM mode: {self.mode}")

        return ReportProviderResult(
            provider=self.name,
            text=text,
            metadata={
                "deterministic": True,
                "provider_type": "mock_llm",
                "provider_version": "v0.6.2-mock-llm-provider",
                "mock_llm_mode": self.mode,
                "real_llm_used": False,
            },
        )

    def _generate_safe_report(self) -> str:
        """生成安全 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The model prediction suggests a possible disease-related risk pattern in the fundus image. This statement is based only on the available structured findings and model output.

## Weak Visual Evidence

The CAM overlay is provided as weak visual evidence only. It may help illustrate regions that contributed to the model prediction, but it should not be interpreted as lesion segmentation, lesion localization, or clinical diagnosis.

## Evidence Boundary

This draft does not establish a clinical diagnosis. It does not claim the presence, absence, type, or location of specific retinal lesions beyond the structured findings.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

    def _generate_unsafe_diagnosis_report(self) -> str:
        """生成包含临床诊断越权表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The patient is diagnosed with diabetic retinopathy based on the fundus image and model prediction.

## Weak Visual Evidence

The CAM overlay is provided as supporting visual evidence.

## Safety Statement

This report is not for clinical use.
"""

    def _generate_unsafe_cam_report(self) -> str:
        """生成包含 CAM / heatmap 夸大表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The model prediction suggests disease-related risk.

## CAM Evidence

The CAM heatmap localizes retinal lesions and shows the lesion area responsible for the disease.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

    def _generate_unsafe_mixed_report(self) -> str:
        """生成同时包含多类不安全表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The patient is diagnosed with diabetic retinopathy. The image quality is validated as sufficient for clinical decision-making.

## CAM Evidence

The CAM heatmap localizes retinal lesions and confirms the abnormal retinal regions.

## Safety Statement

This report can be used as a clinical reference.
"""


def get_report_provider(
    provider_name: ReportProviderName,
    mock_llm_mode: MockLLMMode = "safe",
) -> TemplateProvider | MockLLMProvider:
    """根据名称创建报告生成 Provider。

    Args:
        provider_name: Provider 名称，目前支持 "template" 和 "mock_llm"。
        mock_llm_mode: 当 provider_name 为 "mock_llm" 时使用的 Mock 输出模式。

    Returns:
        TemplateProvider | MockLLMProvider: 对应的 Provider 实例。

    Raises:
        ValueError: 当 provider_name 不受支持时抛出。
    """
    if provider_name == "template":
        return TemplateProvider()

    if provider_name == "mock_llm":
        return MockLLMProvider(mode=mock_llm_mode)

    raise ValueError(f"Unsupported report provider: {provider_name}")
