"""v0.6.1 报告生成 Provider 抽象。

本模块只提供确定性的报告生成 Provider：

- TemplateProvider：确定性模板报告生成器，用作安全回退路径。
- MockLLMProvider：确定性 Mock LLM 生成器，用于测试安全检查器。

真实 LLM Provider，例如 OpenAIProvider、ClaudeProvider 或本地模型 Provider，
刻意延后到 v0.6.2，以避免 v0.6.1 被 API Key、网络调用、成本和输出不稳定性干扰。
"""

from __future__ import annotations

import os
import urllib.error
import urllib.request
from dataclasses import dataclass
from typing import Any, Literal


MockLLMMode = Literal["safe", "unsafe_diagnosis", "unsafe_cam", "unsafe_mixed"]
ReportProviderName = Literal["template", "mock_llm", "real_llm"]


@dataclass(frozen=True)
class ReportProviderResult:
    """Provider 生成结果。

    Attributes:
        provider: Provider 名称，例如 "template" 或 "mock_llm"。
        text: 生成出的 Markdown 报告草稿。
        metadata: 与本次生成相关的元信息，例如 mock 模式、是否确定性、是否调用真实 LLM。
    """

    provider: str
    text: str
    metadata: dict[str, object]


class TemplateProvider:
    """确定性模板报告生成器。

    该 Provider 用作安全回退路径。当 Mock LLM 草稿未通过 safety checker 时，
    renderer 应回退到该模板报告，避免不安全文本进入最终 report.html。
    """

    name = "template"

    def generate(self, prompt: str, case_data: dict[str, Any] | None = None) -> ReportProviderResult:
        """生成保守的模板式病例报告草稿。

        Args:
            prompt: 受约束 prompt。模板 Provider 当前不依赖 prompt 内容，但保留该参数以统一接口。
            case_data: 病例结构化数据，通常来自 prediction.json、findings.json、validation.json 等。

        Returns:
            ReportProviderResult: 确定性的模板报告草稿及其生成元信息。
        """
        case_data = case_data or {}

        prediction = case_data.get("prediction", {})
        findings = case_data.get("findings", {})

        predicted_label = prediction.get("predicted_label", "not available")
        confidence = prediction.get("confidence", "not available")

        text = f"""# Evidence-Bottleneck Case Report Draft

## Generation Mode

This report was generated by the deterministic template provider.

## Model Prediction

- Predicted label: {predicted_label}
- Confidence: {confidence}

## Structured Findings

The report is based only on structured findings available in the case artifact.

Findings summary:

{findings if findings else "No structured finding summary was provided."}

## Evidence Boundary

CAM or heatmap outputs are treated as weak visual evidence only. They are not lesion segmentation, lesion localization, or clinical diagnosis.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

        return ReportProviderResult(
            provider=self.name,
            text=text,
            metadata={
                "deterministic": True,
                "provider_type": "template",
                "provider_version": "v0.6.2-template-provider",
                "fallback_capable": True,
            },
        )


class MockLLMProvider:
    """确定性 Mock LLM 报告生成器。

    该 Provider 不调用真实 LLM，而是用固定文本模拟不同类型的 LLM 输出。
    主要目的不是生成高质量报告，而是为 safety_checker.py 提供可复现测试样例。
    """

    name = "mock_llm"

    def __init__(self, mode: MockLLMMode = "safe") -> None:
        """初始化 Mock LLM Provider。

        Args:
            mode: Mock 输出模式。
                - safe: 安全草稿，应通过 safety checker。
                - unsafe_diagnosis: 包含临床诊断越权表述。
                - unsafe_cam: 包含 CAM / heatmap 夸大表述。
                - unsafe_mixed: 同时包含多类不安全表述。
        """
        self.mode = mode

    def generate(self, prompt: str, case_data: dict[str, Any] | None = None) -> ReportProviderResult:
        """生成确定性的 Mock LLM 报告草稿。

        Args:
            prompt: 受约束 prompt。Mock Provider 当前不解析 prompt，但保留该参数以模拟真实 Provider 接口。
            case_data: 病例结构化数据。当前 Mock 输出不依赖该字段，后续可用于构造更贴近真实 case 的草稿。

        Returns:
            ReportProviderResult: Mock LLM 报告草稿及其生成元信息。

        Raises:
            ValueError: 当 mock mode 不受支持时抛出。
        """
        if self.mode == "safe":
            text = self._generate_safe_report()
        elif self.mode == "unsafe_diagnosis":
            text = self._generate_unsafe_diagnosis_report()
        elif self.mode == "unsafe_cam":
            text = self._generate_unsafe_cam_report()
        elif self.mode == "unsafe_mixed":
            text = self._generate_unsafe_mixed_report()
        else:
            raise ValueError(f"Unsupported mock LLM mode: {self.mode}")

        return ReportProviderResult(
            provider=self.name,
            text=text,
            metadata={
                "deterministic": True,
                "provider_type": "mock_llm",
                "provider_version": "v0.6.2-mock-llm-provider",
                "mock_llm_mode": self.mode,
                "real_llm_used": False,
            },
        )

    def _generate_safe_report(self) -> str:
        """生成安全 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The model prediction suggests a possible disease-related risk pattern in the fundus image. This statement is based only on the available structured findings and model output.

## Weak Visual Evidence

The CAM overlay is provided as weak visual evidence only. It may help illustrate regions that contributed to the model prediction, but it should not be interpreted as lesion segmentation, lesion localization, or clinical diagnosis.

## Evidence Boundary

This draft does not establish a clinical diagnosis. It does not claim the presence, absence, type, or location of specific retinal lesions beyond the structured findings.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

    def _generate_unsafe_diagnosis_report(self) -> str:
        """生成包含临床诊断越权表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The patient is diagnosed with diabetic retinopathy based on the fundus image and model prediction.

## Weak Visual Evidence

The CAM overlay is provided as supporting visual evidence.

## Safety Statement

This report is not for clinical use.
"""

    def _generate_unsafe_cam_report(self) -> str:
        """生成包含 CAM / heatmap 夸大表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The model prediction suggests disease-related risk.

## CAM Evidence

The CAM heatmap localizes retinal lesions and shows the lesion area responsible for the disease.

## Safety Statement

This report is not for clinical use. Human review is required before any medical interpretation or downstream decision.
"""

    def _generate_unsafe_mixed_report(self) -> str:
        """生成同时包含多类不安全表述的 Mock 报告草稿。"""
        return """# Guarded LLM Case Report Draft

## Interpretation Summary

The patient is diagnosed with diabetic retinopathy. The image quality is validated as sufficient for clinical decision-making.

## CAM Evidence

The CAM heatmap localizes retinal lesions and confirms the abnormal retinal regions.

## Safety Statement

This report can be used as a clinical reference.
"""


class RealLLMProvider:
    """OpenAI-compatible 真实 LLM Provider。

    该 Provider 通过环境变量读取配置，并调用 OpenAI-compatible chat completions 接口。

    注意：
        - API key 不应写入代码、日志或 safety_report.json。
        - 真实 LLM 输出仍必须经过 RuleBasedSafetyChecker。
        - 本 Provider 只负责生成 draft，不负责安全判断。
    """

    name = "real_llm"

    def __init__(self) -> None:
        """从环境变量读取真实 LLM 配置。"""
        self.api_key = os.getenv("OPHAGENT_LLM_API_KEY")
        self.base_url = os.getenv("OPHAGENT_LLM_BASE_URL", "https://api.openai.com/v1")
        self.model = os.getenv("OPHAGENT_LLM_MODEL")
        self.temperature = float(os.getenv("OPHAGENT_LLM_TEMPERATURE", "0"))
        self.top_p = float(os.getenv("OPHAGENT_LLM_TOP_P", "1"))
        self.timeout_seconds = float(os.getenv("OPHAGENT_LLM_TIMEOUT_SECONDS", "60"))

    def generate(self, prompt: str, case_data: dict[str, Any] | None = None) -> ReportProviderResult:
        """调用 OpenAI-compatible chat completions 接口生成报告草稿。

        Args:
            prompt: 受约束 prompt。
            case_data: 病例结构化数据。当前真实 LLM Provider 不直接使用该字段。

        Returns:
            ReportProviderResult: 真实 LLM 输出及其审计元信息。

        Raises:
            RuntimeError: 当 API key 或 model 未配置，或远程调用失败时抛出。
        """
        if not self.api_key:
            raise RuntimeError("OPHAGENT_LLM_API_KEY is not set.")

        if not self.model:
            raise RuntimeError("OPHAGENT_LLM_MODEL is not set.")

        endpoint = self.base_url.rstrip("/") + "/chat/completions"

        payload = {
            "model": self.model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "You are a cautious medical report drafting assistant. "
                        "You must follow the user's evidence boundary exactly."
                    ),
                },
                {
                    "role": "user",
                    "content": prompt,
                },
            ],
            "temperature": self.temperature,
            "top_p": self.top_p,
        }

        request = urllib.request.Request(
            endpoint,
            data=__import__("json").dumps(payload).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {self.api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )

        try:
            with urllib.request.urlopen(request, timeout=self.timeout_seconds) as response:
                response_data = __import__("json").loads(response.read().decode("utf-8"))
        except urllib.error.URLError as exc:
            raise RuntimeError(f"Real LLM provider request failed: {exc}") from exc

        try:
            text = response_data["choices"][0]["message"]["content"]
        except (KeyError, IndexError, TypeError) as exc:
            raise RuntimeError("Real LLM provider returned an unexpected response format.") from exc

        return ReportProviderResult(
            provider=self.name,
            text=text,
            metadata={
                "deterministic": False,
                "provider_type": "real_llm",
                "provider_version": "v0.6.3-openai-compatible-provider",
                "real_llm_used": True,
                "model_name": self.model,
                "base_url_configured": bool(self.base_url),
                "temperature": self.temperature,
                "top_p": self.top_p,
                "timeout_seconds": self.timeout_seconds,
            },
        )


def get_report_provider(
    provider_name: ReportProviderName,
    mock_llm_mode: MockLLMMode = "safe",
) -> TemplateProvider | MockLLMProvider:
    """根据名称创建报告生成 Provider。

    Args:
        provider_name: Provider 名称，目前支持 "template"、"mock_llm" 和 "real_llm"。
        mock_llm_mode: 当 provider_name 为 "mock_llm" 时使用的 Mock 输出模式。

    Returns:
        TemplateProvider | MockLLMProvider: 对应的 Provider 实例。

    Raises:
        ValueError: 当 provider_name 不受支持时抛出。
    """
    if provider_name == "template":
        return TemplateProvider()

    if provider_name == "mock_llm":
        return MockLLMProvider(mode=mock_llm_mode)

    if provider_name == "real_llm":
        return RealLLMProvider()

    raise ValueError(f"Unsupported report provider: {provider_name}")
